@startuml

actor "Nutzer" as N

component "System" as SYS #orange

N --> SYS: Uses

component "Service 1" <<service>> as S1
component "Service 2" <<service>> as S2

S1 -up-> SYS: Data
S2 <-up- SYS: Data

@enduml
