site_name: Archdoc
theme: material
nav:
  - Introduction & Goals: index.md
  - Constraints: architecture_constraints.md
  - Context & Scope: context_scope.md
  - Soluation Strategy: solution_strategy.md
  - Building Block View: building_block_view.md
  - Runtime View: runtime_view.md
  - Deployment View: deployment_view.md
  - Crosscutting Concepts: crosscutting_concepts.md
  - Architecture Decisions: architecture_decisions.md
  - Quality Requirements: quality_requirements.md
  - Risks & Technical Dept: risks_techdebt.md
  - Glossary: glossary.md
plugins:
  - build_plantuml:
    render: "server" # or "local" for local rendering
    bin_path: "/usr/local/bin/plantuml" # ignored when render: server
    server: "http://www.plantuml.com/plantuml" # official plantuml server
    disable_ssl_certificate_validation: true # for self-signed and invalid certs
    output_format: "png" # or "svg"
    diagram_root: "docs" # should reside under docs_dir
    output_folder: "generated"
    input_folder: "plantuml"
    input_extensions: "" # comma separated list of extensions to parse, by default every file is parsed
markdown_extensions:
  - footnotes
  - attr_list
  - toc:
    permalink: true
